# Generated by Django 4.1 on 2025-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="answers",
            field=models.JSONField(default=dict),
        ),
    ]
