# Generated by Django 4.1 on 2025-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hasTakentest",
            field=models.BooleanField(default=True),
        ),
    ]
