# Generated by Django 4.1 on 2025-01-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_hastakentest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hasTakentest",
        ),
    ]
