# Generated by Django 4.1 on 2025-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_hastakentest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hasTakentest",
            field=models.BooleanField(default=False),
        ),
    ]
