# Generated by Django 5.1.4 on 2025-01-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_hastakentest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='evaluation',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
